[env]
# XMAKE_CONFIGDIR = '.dist'
XMAKE_CONFIGDIR = '.cache'

[tools]
node = "25.3.0"
bun = "1.3.6"
deno = "2.6.4"
uv = "0.9.24"
ubi = "0.8.4"

[tools."github:xmake-io/xmake"]
version = "3.0.4"

[tools."github:xmake-io/xmake".platforms]
linux-x64 = { asset_pattern = "xmake-bundle-v*.linux.x86_64", bin = "xmake" }
windows-x64 = { asset_pattern = "xmake-v*.win64.zip", bin_path = "xmake" }
